import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/Link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Tarot Readings with Chara | Upleveled',
    template: '%s | Upleveled',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/product">Readings</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
