import FaceWash from '/facewash/FaceWash';
import Image from 'next/image';

export const metadata = {
  title: 'Beauty Products',
  description: 'Generated by create next app',
};
export default function ProductsPage() {
  return (
    <div>
      <h1>Beauty Products</h1>
      <a href="/facewash" data-test-id="product-facewash">
        <FaceWash />
      </a>
      <a href="/moisturizer" data-test-id="product-moisturizer">
        <div>Moisturizer</div>
      </a>
      <a href="/eyecream" data-test-id="product-eyecream">
        <div>Eye Cream</div>
      </a>
      <a href="/retinol" data-test-id="product-retinol">
        <div>Retinol</div>
      </a>
    </div>
  );
}
